name: Test

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make -j4
    - name: Test
      run: |
        cd build
        make test
    - name: Example
      run: |
        cd build
        ./example
